### ISSUE TITLE
bug: current champion is null after champion creation.

### ISSUE THREAD

**Issue by vczyx** [5tarlight/jamza#14]
An exception occurred after creating a new champion.
![image](https://user-images.githubusercontent.com/74102978/181096991-8a1be652-c788-43f6-84a9-cf8f93bbb6ef.png)
This is the process of moving to the test map after creating a champion.
Player.current is null.

**Comment by 5tarlight** [comment]
Champion instance is not assigned when champion created.

**Comment by 5tarlight** [comment]
fixed in #13
